### ISSUE TITLE
file ignore doesnt work

### ISSUE THREAD

**Issue by paigeadelethompson** [impresscms-dev/phpdocs-wiki-update-action#212]

**Comment by paigeadelethompson** [comment]
I need to skip files and it won't no matter what glob I try tried even with just * and ** neither of those even work 

```
name: Automatic update project documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting project code...
        uses: actions/checkout@v2
      - name: Update wiki with PHP project documentation
        uses: impresscms-dev/phpdocs-wiki-update-action@v2.2
        with:
          engine: clean/phpdoc-md
          class_root_namespace: pscr\extensions\pscr_content\
          include: |
            pscr\extensions\pscr_content\**
          ignored_files: |
           /home/runner/work/_temp/*/extensions/pscr_content/app_settings.php
```
