### ISSUE TITLE
Error: No classes matches include rules

### ISSUE THREAD

**Issue by everton3x** [impresscms-dev/phpdocs-wiki-update-action#3]
I am trying to integrate this Action into my [PHP project](https://github.com/everton3x/html-object-model/), however I get the following error every time, no matter how I modify wiki.yml:
**[error] Error: No classes matches include rules**
This is my wiki.wml file
```yaml
name: Automatic update project documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting project code...
        uses: actions/checkout@v2
      - name: Updating wiki...
        uses: impresscms-dev/phpdocs-wiki-update-action@master
        with:
          wiki_github_update_token: ${{ secrets.WIKI_GITHUB_UPDATE_TOKEN }}
          wiki_github_update_user: ${{ secrets.WIKI_GITHUB_UPDATE_USER }}
          engine: clean/phpdoc-md
          class_root_namespace: Html Object Model
          include: |
            \\HtmlObjectModel\\**\\
```
These are the errors:
![image](https://user-images.githubusercontent.com/582620/76793489-e1921980-67a3-11ea-9fbe-29689d4b4b6a.png)

This is my composer.json:
```json
{
    "name": "everton3x/html-object-model",
    "description": "Library for creating object-oriented HTML entities, in the Document Object Model style.",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Everton da Rosa",
            "email": "everton3x@gmail.com",
            "homepage": "https://everton3x.github.io",
            "role": "Developer"
        }
    ],
    "support": {
        "issues": "https://github.com/everton3x/html-object-model/issues",
        "docs": "https://everton3x.github.io/html-object-model/"
    },
    "require": {
        "php": "^7.4"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.16",
        "squizlabs/php_codesniffer": "*",
        "phpmd/phpmd": "^2.8",
        "sebastian/phpcpd": "^5.0",
        "phpstan/phpstan": "^0.12.14",
        "phpunit/phpunit": "^9.0",
        "phpunit/php-code-coverage": "^8.0"
    },
    "autoload-dev": {
        "psr-4": {
            "HtmlObjectModel\\": "src"
        }
    }
}
```
My classes (namespace HtmlObjectModel) are inside the src directory, under the project's root directory.

I don't really know what's going on. I already changed the `include` in the most diverse ways and nothing solves it.

**Comment by MekDrop** [comment]
@everton3x sorry, I left a bug in example. `include` section doesn't needs have double \ in namespaces

I tried to fork and use this configuration and it seems that worked:
```yaml
name: Automatic update project documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting project code...
        uses: actions/checkout@v2
      - name: Updating wiki....
        uses: impresscms-dev/phpdocs-wiki-update-action@master
        with:
          wiki_github_update_token: ${{ secrets.WIKI_GITHUB_UPDATE_TOKEN }}
          wiki_github_update_user: ${{ secrets.WIKI_GITHUB_UPDATE_USER }}
          engine: clean/phpdoc-md
          class_root_namespace: Html Object Model
          include: |
            HtmlObjectModel\**
```

And I got such result:
![image](https://user-images.githubusercontent.com/342641/76863531-4c0c8d80-6868-11ea-8e22-96a844619916.png)
